name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - flask=3.0.2=pyhd8ed1ab_0
  - flask_cors=3.0.10=pyhd3eb1b0_0
  - watchdog=3.0.0=py311h38be061_1
  - jupyter
  - matplotlib
  - numpy
  - psycopg2
  - pylint
  - pip:
      - werkzeug==2.3.6
